### ISSUE TITLE
Where do you host your wiki and your personal site? How do you manage deploys?

### ISSUE THREAD

**Issue by mtshv** [nikitavoloboev/ama#12]

**Comment by nikitavoloboev** [comment]
I host the wiki with [GitBook](https://www.gitbook.com) and my site is hosted with [Netlify](https://www.netlify.com) and built with [Hugo](https://github.com/gohugoio/hugo).

For, any [push to master](https://github.com/nikitavoloboev/nikitavoloboev.xyz) will build the site and update it.

For the wiki it's the same but any push to my [knowledge repo](https://github.com/nikitavoloboev/knowledge) will rebuild the wiki.

**Comment by mtshv** [comment]
Thank you for the answer @nikitavoloboev 
I am going to try Netlify :)
