### ISSUE TITLE
Several questions about MacOS setups.

### ISSUE THREAD

**Issue by oltv00** [nikitavoloboev/ama#13]
Hello!
I have the several questions about MacOS setups.
1. Do you use the option `Automatically hide and show the menu bar`
![image](https://user-images.githubusercontent.com/14943414/40864890-69cbce1c-65fe-11e8-935f-09f593e84813.png)
2. Do you use the option `Automatically hide and show the Dock`
![image](https://user-images.githubusercontent.com/14943414/40864930-893d7368-65fe-11e8-85c6-006c3b03caa7.png)
3. What resolution do you use on your MacBook Pro?
I mean the settings on the screenshot below.
![image](https://user-images.githubusercontent.com/14943414/40865045-19567d3c-65ff-11e8-9409-e2934193a439.png)

**Thanks in advance for your reply!**

**Comment by nikitavoloboev** [comment]
1. 
![2018-06-02 at 00 04](https://user-images.githubusercontent.com/6391776/40865432-88c2ebda-65f8-11e8-90a8-d7b18568521b.png)

2. 
![2018-06-02 at 00 04](https://user-images.githubusercontent.com/6391776/40865446-91e1f986-65f8-11e8-824d-62b000821fa3.png)

3. 
![2018-06-02 at 00 04](https://user-images.githubusercontent.com/6391776/40865454-99c60318-65f8-11e8-8a28-fac49a2b2318.png)

**Comment by oltv00** [comment]
Thanks!
