### ISSUE TITLE
GNU/Linux

### ISSUE THREAD

**Issue by fturco** [nikitavoloboev/ama#15]
Have you ever considered switching to GNU/Linux?

**Comment by nikitavoloboev** [comment]
Never considered it really as my macOS environment is extremely well optimized for my own use and I know that Linux simply doesn't have the tools I use day to day (i.e. Keyboard Maestro).

Although if I did use Linux, I would certainly be using [NixOS](https://nixos.org) and I use Nix package manager on macOS.

Linux is amazing for servers but I love how extensive and rich the macOS/iOS ecosystems are and there is a really huge cost to switching.
