### ISSUE TITLE
Can you open source some of your alfred workflows?

### ISSUE THREAD

**Issue by yqrashawn** [nikitavoloboev/ama#2]
Like `nikivi.styaing.on.top`, `nikivi.search-the-web`, `nikivi.search.files". Maybe it's won't work for others. But I'd like to see.

**Comment by nikitavoloboev** [comment]
Of course. Here are some workflows I use. They are very tailored to my use cases though thus I didn't upload them. Hope you find them interesting. 

[multi website presets](https://transfer.sh/ot9R0/a-multi-website-presets.alfredworkflow)
[search the web](https://transfer.sh/Q3YR4/a-search-the-web.alfredworkflow)
[search files](https://transfer.sh/14oERn/a-search-files.alfredworkflow)
[search for content](https://transfer.sh/14giFj/a-search-for-content.alfredworkflow)
[search web with selection](https://transfer.sh/9seEt/a-search-web-with-selection.alfredworkflow)
[wifi](https://transfer.sh/XurJO/a-wifi.alfredworkflow)

**Comment by yqrashawn** [comment]
Thanks. 👏
