### ISSUE TITLE
Do you have a favourite quote? One you live by or think of often?

### ISSUE THREAD

**Issue by leovogel** [nikitavoloboev/ama#23]

**Comment by nikitavoloboev** [comment]
I list my favorite quotes [here](https://nikitavoloboev.xyz/likes/).

My favorite of all being:

> We thought of life by analogy with a journey, a pilgrimage, which had a serious purpose at the end, and the thing was to get to that end, success or whatever it is, maybe heaven after you’re dead. But we missed the point the whole way along. It was a musical thing and you were supposed to sing or to dance while the music was being played.
