### ISSUE TITLE
What have you changed your mind about in the last few years? Why?

### ISSUE THREAD

**Issue by leovogel** [nikitavoloboev/ama#28]

**Comment by nikitavoloboev** [comment]
Depth over breadth in learning.

**Comment by devnoname120** [comment]
@nikitavoloboev Did it change Depth → Breadth or the other way around?

**Comment by nikitavoloboev** [comment]
Sadly been all over the place recently. My [Notion's goals board](https://www.notion.so/nikitavoloboev/e462537d8f3d40c095ea67091ca91f45?v=1006717e984a4243b198bcad5bf05198) and task manager is trying to keep it together. :)
