### ISSUE TITLE
Java language does not show

### ISSUE THREAD

**Issue by jsroyal** [nikitavoloboev/ama#3]
![image](https://user-images.githubusercontent.com/10773353/27262883-99c2af34-547d-11e7-9223-6e8d1b8337b8.png)
Want to core Java learn.

**Comment by nikitavoloboev** [comment]
You can scroll for more options that shown there with arrow keys or trackpad.

[Here](https://learn-anything.xyz/programming/programming-languages/java) is a map for Java. :)

**Comment by jsroyal** [comment]
Oh' Sorry. I just missed scrolled.
Thank you @nikitavoloboev
