### ISSUE TITLE
How do you decide between making a repo for one of your lists and putting it into your `knowledge` gitbook instead?

### ISSUE THREAD

**Issue by obahareth** [nikitavoloboev/ama#35]
For example, I see your gitbook has a page your VS Code extensions, but you have a dedicated repo for macOS apps.

**Comment by nikitavoloboev** [comment]
I mostly keep everything in my wiki. my-mac-os and my-ios were made before I even had a wiki. Also my-mac-os repo contains files like BTT preset or themes and I only want to keep markdown files in my wiki.
