### ISSUE TITLE
How do you tag your posts?

### ISSUE THREAD

**Issue by vladola** [nikitavoloboev/ama#37]
I don't see any tagging in your posts nor in github. I'm assuming you don't use them? If so, how come? I find tagging wonderful for connecting a central idea across different categories.

**Comment by nikitavoloboev** [comment]
What kind of tags are you referring to?

**Comment by nikitavoloboev** [comment]
Can you give an example of tags you use?

I do use tags in some places like file names for books and research papers.

![2019-01-17 at 13 36](https://user-images.githubusercontent.com/6391776/51319270-db4bc480-1a5c-11e9-88c7-3c905688f20e.png)

**Comment by vladola** [comment]
Have a look [here][1] for an example of how I use tags. Other times it's useful to connect different notes which are in different categories but form a common trend of thought.

BTW, a more technical question: how do you write internal links in your wiki? All markdown editors I tried don't really 'get' internal links (like ../category/file.md#subheading). So with no auto-complete I'm screwed if I have a typo.

[1]: https://praxis.fortelabs.co/a-complete-guide-to-tagging-for-personal-knowledge-management/
