### ISSUE TITLE
VSCode Night Blue Theme

### ISSUE THREAD

**Issue by johnletey** [nikitavoloboev/ama#38]
I was an extreme fan of your VSCode Night Blue Theme, but it seems to have been deleted. Would you kindly consider republishing it please?

**Comment by nikitavoloboev** [comment]
> Would you kindly consider republishing it please?

I wish I could. But I just looked and I deleted it for good. 😞

I did have a valid reason though, [Monokai Night](https://github.com/fabiospampinato/vscode-monokai-night) theme is quite amazing, you can try it.

**Comment by johnletey** [comment]
Bummer ... I'll definitely have a look at the Monokai Night theme

Thanks though!

**Comment by johnletey** [comment]
Wow ... the Monokai Night theme is a real treasure

The only problem is that I'm still stuck on your Night Blue iTerm ... do you know of a way to change the background of the VSCode window (but keep everything else the same) so that it matches my terminal?

**Comment by nikitavoloboev** [comment]
You’re in luck 

https://github.com/nikitavoloboev/my-mac-os/blob/master/iterm/README.md

**Comment by johnletey** [comment]
Awesome!
