### ISSUE TITLE
Help migrating over to Nix

### ISSUE THREAD

**Issue by johnletey** [nikitavoloboev/ama#39]
Hey Nikita,

I'm a huge fan of Homebrew and I use it almost every day, but I've heard great things about Nix ... would you recommend migrating ... is it worth it?

If you do, I've found the documentation very hard to understand ... do you have any tips for someone on a Mac to help them get started/install Nix/install packages using Nix?

**Comment by nikitavoloboev** [comment]
> would you recommend migrating ... is it worth it?

I'd say it's worth learning Nix for sure. I use both Nix and brew currently but most of the packages I install with Nix [declaratively](https://github.com/nikitavoloboev/dotfiles/blob/master/nix/darwin.nix#L6).



> I've found the documentation very hard to understand

You're not alone 😅 I haven't finished the entire documentation myself but I would recommend joining `#nixos` group on Freenode (it's very active).

 

> do you have any tips for someone on a Mac to help them get started/install Nix/install packages using Nix?

I have an article I plan to release hopefully soon that targets that (Introduction to Nix on macOS).

**Comment by johnletey** [comment]
> I'd say it's worth learning Nix for sure. I use both Nix and brew currently but most of the packages I install with Nix [declaratively](https://github.com/nikitavoloboev/dotfiles/blob/master/nix/darwin.nix#L6).

Could you explain to me why [nix-darwin](https://github.com/LnL7/nix-darwin) is needed?

> I have an article I plan to release hopefully soon that targets that (Introduction to Nix on macOS).

Great! Looking forward to it!

**Comment by nikitavoloboev** [comment]
> [nix-darwin](https://github.com/LnL7/nix-darwin)

Lets me specify in Nix my macOS configuration (packages to install + other stuff).

I don't use home-manager currently.

**Comment by johnletey** [comment]
> Lets me specify in Nix my macOS configuration (packages to install + other stuff).

I see ... and how exactly is this different from simply just installing packages via Nix

**Comment by nikitavoloboev** [comment]
> how exactly is this different from simply just installing packages via Nix

With brew you do `brew install <package>`.

In nix you can do the same with `nix-env -f '<nixpkgs>' -iA <package>`

But alternatively you can write the `state` you want your macOS to be in (packages installed, config) in a `.nix` file(s), in my case it's one [darwin.nix]([declaratively](https://github.com/nikitavoloboev/dotfiles/blob/master/nix/darwin.nix#L6)) file.

Then you `apply` the configuration on the system. With `darwin-rebuild switch` in nix-darwin case. And you have your macOS in the state defined by nix. Nix can do a lot more though, I am still learning.

**Comment by johnletey** [comment]
Wow ... that's extremely useful ... I think I'll give Nix a try ... I'll slowly start transitioning all of my configurations over to Nix

One last question:

> In nix you can do the same with `nix-env -f '<nixpkgs>' -iA <package>`

With nix-darwin, do you still run the above command to install packages, or do you run something else?

**Comment by nikitavoloboev** [comment]
> With nix-darwin, do you still run the above command to install packages

You can run this command without nix-darwin. This is 'install a package' command provided by Nix.

**Comment by johnletey** [comment]
I see! Also, do you have your nix configurations aliased? Or how do you set your nix configuration files to inside your dotfiles?

**Comment by nikitavoloboev** [comment]
> do you have your nix configurations aliased

![2019-02-25 at 17 31](https://user-images.githubusercontent.com/6391776/53352557-440f4200-3923-11e9-819c-4b2a4a34a2fc.png)

I have the file + a shell always open so I can edit the file and run `darwin-rebuild switch` in my right split.

**Comment by johnletey** [comment]
Got it ... but I was asking exactly how you tell nix-darwin that your configuration is at `~/dotfiles/nix/darwin.nix` ... cause it told me that my configuration is at `.nixpkgs/darwin-configuration.nix`

**Comment by nikitavoloboev** [comment]
I don't remember the command I ran for that. I asked in #nix-darwin Freenode group. Should have documented it. 😞

**Comment by johnletey** [comment]
Bummer ... anyways, thanks for the help! Also, my iTerm looks different than yours, do you mind posting your `com.googlecode.iterm2.plist` (you can tell iTerm where to save the file in preferences)

**Comment by nikitavoloboev** [comment]
https://transfer.sh/OuLKE/com.googlecode.iterm2.plist

**Comment by johnletey** [comment]
Thanks!

**Comment by nikitavoloboev** [comment]
@johnletey Was just released https://www.softinio.com/post/moving-from-homebrew-to-nix-package-manager/ :)

**Comment by johnletey** [comment]
@nikitavoloboev Thanks so much ... reading now
