### ISSUE TITLE
What is your Terminal app?

### ISSUE THREAD

**Issue by TGNYC** [nikitavoloboev/ama#4]
As seen here:

![](https://camo.githubusercontent.com/7ea8dde346354bf2eeed86175a76539498afde3f/687474703a2f2f692e696d6775722e636f6d2f4a56334e64557a2e6a7067)

**Comment by nikitavoloboev** [comment]
[iTerm 2](https://iterm2.com) :)

You can get the borderless look in the settings of it.

**Comment by TGNYC** [comment]
Cool. What was that `sf` command you did to display the sys info?

**Comment by nikitavoloboev** [comment]
[Screenfetch](https://github.com/KittyKatt/screenFetch)
