### ISSUE TITLE
Posture

### ISSUE THREAD

**Issue by johnletey** [nikitavoloboev/ama#40]
I was having a read through you wiki, and I came across the following:

> Always have good posture. Sit properly and upright, don't bend my back/spine.

Coming from a person that struggles with this, how exactly do you enforce this and make sure that you always have good posture?

**Comment by nikitavoloboev** [comment]
> how exactly do you enforce this and make sure that you always have good posture?

Practicing mindfulness throughout the day is how I do it. Try to be aware of my posture and improve the ergonomics of my work place and tools where I can (like using a standing desk if possible or standing up throughout the day).

**Comment by johnletey** [comment]
Got it ... thanks!

> like using a standing desk if possible or standing up throughout the day

I can see that this helps if you are on a computer a lot (which I am) ... but I also do some work on paper, can you still stand and write ... is it uncomfortable (have you had experience doing this)?

**Comment by nikitavoloboev** [comment]
> can you still stand and write

Yes you can :)

**Comment by nikitavoloboev** [comment]
And no, there is no discomfort in that

**Comment by johnletey** [comment]
> Yes you can :)

Great!

> And no, there is no discomfort in that

Great ... that clears up everything that I was worried about!
