### ISSUE TITLE
What is your daily routine?

### ISSUE THREAD

**Issue by vikepic** [nikitavoloboev/ama#42]
> When do you check your focus boards? Do you meditate before bed? When do you check the news? Do you have any scheduled breaks?

First of all, love your work!

My question is about how do you go about your work day.

I am curious as to how do you distribute your time to get the most out of your day. I am a freelancer myself and I struggle with how to organise myself and my day, and I thought I could get some inspiration with your routine.

Thanks!

**Comment by nikitavoloboev** [comment]
> When do you check your focus boards?

I have scheduled day/week/month reviews where I force myself to set/overview goals in my Focus board.
 
![2019-03-28 at 12 50](https://user-images.githubusercontent.com/6391776/55155600-19015380-5158-11e9-9ec5-df8a3449c0aa.png)

I also check it occasionally throughout the day to keep myself focused on the goals I have. I also [create events based on the goals I have](https://wiki.nikitavoloboev.xyz/focusing).


> Do you meditate before bed?


I don't. I don't really practice focused mindfulness (although I plan to start at some point). I do focus on being mindful and bringing mindfulness in any activity or thought I have. So it's more of an ongoing process.



> When do you check the news?

I have [scheduled breaks](https://github.com/nikitavoloboev/knowledge/blob/master/focusing/focusing.md#focus-sessions). In those breaks I can check the news if I want to.



> Do you have any scheduled breaks?

Answered above. 🙂

**Comment by vikepic** [comment]
Thanks for the response ❤️
