### ISSUE TITLE
Bullet Journaling

### ISSUE THREAD

**Issue by johnletey** [nikitavoloboev/ama#44]
What's your opinion on [Bullet Journaling](https://bulletjournal.com)?

I'm reading the official book and I'm loving it so far

**Comment by johnletey** [comment]
@nikitavoloboev This would really help with journaling in Day One and your monthly looking back reports in your wiki

**Comment by nikitavoloboev** [comment]
I read about it briefly. Will look into it again but I believe their system is physical so if I do bring ideas to it, it would have to be done digitally which shouldn't be a problem.



> This would really help with journaling in Day One

I don't much journal in Day One any more. Only very private experiences are written down there but those are rare.



> I'm reading the official book and I'm loving it so far

Would love to read your thoughts on the method & how you plan or are using ideas from it in your workflow. Will be a reason to release that new shiny blog of yours.

**Comment by johnletey** [comment]
> Will look into it again but I believe their system is physical

That's kind of what I like about it ... though it would be nice if there was an app that followed the same principles

> Will be a reason to release that new shiny blog of yours.

This keeps coming up ...
