### ISSUE TITLE
DRM (Digital Rights Management)

### ISSUE THREAD

**Issue by fturco** [nikitavoloboev/ama#46]
What's your opinion a DRM (Digital Rights Management)? Do you avoid buying digital content with DRM? Do you remove DRM? What about social DRM (watermarks)?

**Comment by nikitavoloboev** [comment]
Don't really think about it. 

I pirate some things, buy the rest. For some things where it makes sense renting content like music (with Spotify) I do it. 

I do like use non DRM things where possible.
