### ISSUE TITLE
How do you organize todos across multiple apps?

### ISSUE THREAD

**Issue by maltsev** [nikitavoloboev/ama#48]
According to your wiki, you use Trello, 2Do, and MindNone to store todos, which seems to be quite overlapping. How do you decide where to put a new todo? And in general, how do you track projects, which might have many todos and other corresponding information?

**Comment by nikitavoloboev** [comment]
I use 2Do for most of my tasks. Projects tasks are usually done via GitHub (issues) and sometimes Trello (general projects). MindNode I use as a thinking board. Just put things in there, work on it, then erase the entire map.
