### ISSUE TITLE
what are your clever techniques to learn/research a completely new topic?

### ISSUE THREAD

**Issue by avimehenwal** [nikitavoloboev/ama#49]
Hey Hello, first of all **congratulations** for all the wonderful things you have done and accomplished. Well earned Kudos :1st_place_medal:  please keep it up :+1: It inspires poor souls like ours XD 

I spend most of my time searching things on internet (apparently I still know nothing about this world ) and I want to reflect on it make researching process little bit easy for me, thats when I came across one of your fine works [learn-anything.](https://learn-anything.xyz/programming/programming-languages/javascript)

And so comes my question, what are your smart techniques that you implement (or would like to implement !) to learn about a totally new topic?
Consider a hypothetical situation like, somebody challenges you to learn everything about _Feng Zheng_, or _wormholes_ or something like this so bizzare, how do you usually break down the topic at hand?

> Is there a workflow we can make to research to totally bizarre topics ? 

Hope it make sense :D

**Comment by nikitavoloboev** [comment]
Thanks for the kind words @avimehenwal 

One thing I do is try to track things I am learning or want to learn. This doesn't include learning things that I need to learn to solve a particular task, that learning I do on the spot by deconstructing what it is I want to solve and what things I need to know to get there.

Currently I track topics Im learning and want to learn in [Trello](https://trello.com/b/cu32qF3q). I hope to move it to Learn Anything once we build the feature of knowledge graph and tracking progress on a knowledge graph of topics. Same goes for ideas to build.

I also have a repo [build to learn](https://github.com/nikitavoloboev/build-to-learn) that I use as starting point for playing around with things and testing ideas. The goal is to remove friction in anything I do.

As for your question of learning bizarre topics or any topic whatsoever, Id probably start with a wiki article on it. Then search resources and learn it. I like searching reddit and finding threads/comments there. Lots of resources in [my wiki](https://github.com/nikitavoloboev/knowledge) for many topics so I use that now. Have enough resources and topics to learn to last me a life time. 🙃

**Comment by nikitavoloboev** [comment]
You might also find useful these links

https://wiki.nikitavoloboev.xyz/research/solving-problems

https://wiki.nikitavoloboev.xyz/ideas

https://wiki.nikitavoloboev.xyz/focusing
