### ISSUE TITLE
Remapping Ctrl and ESC

### ISSUE THREAD

**Issue by chrisalcantara** [nikitavoloboev/ama#50]
Using Karabiner (or another app), what do you think is the best way I can get the following behavior with my Ctrl key: 

`Hold Ctrl -> Ctrl`
`Tap Ctrl -> Escape`

I previously used Hammerspoon to do this, but it kept clashing with key rebindings I made in Keyboard Maestro for the Ctrl key. Any advice?

**Comment by nikitavoloboev** [comment]
would ask this in [telegram group](https://t.me/karabinermac)
