### ISSUE TITLE
Routines, Habits, Lessons Learned

### ISSUE THREAD

**Issue by AndersonZacharyT** [nikitavoloboev/ama#51]
Hi Nikita! Long time fan, first time caller. I've enjoyed watching you build things and have landed on your page now and then for quite some time. Noticed this AMA and just had to give it a shot since you said I could ask anything, and I've been wondering for a while.

You're well spoken, prolific and seem unwaveringly consistent: all traits that I admire and consequently pursue. I'd love if you could tell me more about what your days and your habits look like. This probably sounds crazy, but bear with me.

Do you have any rituals when you sit down to learn something new? Would that ritual differ from building something using existing skills? What are your sleep habits? Stimulants? Exercise? Do you meditate?  No need to answer any of these in particular, I'd best summarize my question as **what is it that you do that you believe benefits your wellness, productivity, and ability to visualize goals worth sticking to, as well as sticking to them? What's one habit you believe would hurt you the most to lose?**

I hope that made sense. I saw your other ama routine question, and I know you literally have a knowledge base that answers a lot of this, so if that's the answer, that's good enough for me, just figured I'd drop you a line. I hope you've been well through this unprecedented time. Thank you for your many contributions!

**Comment by nikitavoloboev** [comment]
Hey Zach. Thanks for kind words.

I try my best to refine and follow a [set of rules](https://wiki.nikitavoloboev.xyz/focusing/rules) I defined for myself. That's as close I get to having a routine. 

> Do you have any rituals when you sit down to learn something new? Would that ritual differ from building something using existing skills? What are your sleep habits? Stimulants? Exercise? Do you meditate?

It should answer all these questions. I do want to build an app for defining and easily following through processes (I now list them in [wiki](https://wiki.nikitavoloboev.xyz/focusing/processes)) but I want a nicer web app + native apps for this. In there I can define my morning or evening routine amongst other routines.

There's lots of things I want to build to perfect things like learning new things [learn anything](https://github.com/learn-anything/learn-anything) to solve this. I want to track all topics I am learning and want to learn as well as all ideas I am working on now and want to build later with full searchability of everything.

> What's one habit you believe would hurt you the most to lose?

Maybe not a habit but I think the amount of time I invested into tools and optimizations is paying off big time for me. [Karabiner](https://wiki.nikitavoloboev.xyz/macos/macos-apps/karabiner) specifically saved me 1000+ hours I believe.
