### ISSUE TITLE
your wiki's impact on job finding

### ISSUE THREAD

**Issue by yosoyuva** [nikitavoloboev/ama#52]
Do you have more ease to find jobs with your wiki public. Is this something you get asked on jobs interview ?

**Comment by nikitavoloboev** [comment]
I wrote the wiki for myself and others to use. Never was asked about my wiki per say on the interview but I'm sure it's something that people notice if they view my github profile (it's also mentioned in my cv).

As for finding work itself, I document my approach + links that helped me here:

https://wiki.nikitavoloboev.xyz/work/finding-work

**Comment by yosoyuva** [comment]
thank you, I discovered your wiki yesterday and it inspired me to start one too. I share the idea that Knowing something is knowing where it is written down, so you don't have to "know" the majority of informations you need as you can find them just by a quick google search, but this wiki thing is more powerful
