### ISSUE TITLE
You know anything about using vimwiki and github pages with jekyll as a possible digital garden solution?

### ISSUE THREAD

**Issue by sdondley** [nikitavoloboev/ama#53]
I've had an interest in documenting and sharing my notes easily for a long time. But it is too much of a pain in the ass. It needs to be painless. I'm super lazy.

I'm eyeing github pages with jekyll combined with vimwiki to help update and maintain my documents. Wondering if you might have any advice or tips regarding this as a possible solution.

**Comment by nikitavoloboev** [comment]
GitHub pages or Netlify can be used to host any static content so it doesn't matter what you use. Netlify has better UX though.

As for the tool to maintain documents, I haven't tried vimwiki but I use vim inside Sublime Text that I love using. Wrote about it [here](https://wiki.nikitavoloboev.xyz/other/wiki-workflow).

The biggest tip is make it super fast to open any note in your wiki to make an edit. I achieve this with Alfred workflow.

**Comment by nikitavoloboev** [comment]
Came across https://lobste.rs/s/gynavy/using_vimwiki_for_note_taking

**Comment by sdondley** [comment]
Checking out Alfred is on my list of things to investigate. 

The nice thing about vimwiki is it makes it exceptionally easy to create hyperlinked pages that are nicely formatted with markdown and navigate between them in the editor. I have a site set up already at Steve.dondley.com with github pages. I’m just looking for a script or two that will help me integrate the notes into Jekyll, which I don’t know much about. Not sure what the best approach is yet.

**Comment by nikitavoloboev** [comment]
Check this out https://github.com/maximevaillancourt/digital-garden-jekyll-template

**Comment by sdondley** [comment]
Thanks, I’ll look into it. If I get a good solution pulled together, I’ll post a recipe about it on Reddit.

**Comment by sdondley** [comment]
Well, it took an ugly dollop of Perl glue, but I got something functional working at https://steve.dondley.com/notes/

It's slightly convoluted where I have vimwiki generate a "jekyll-friendly" version of markdown (that's where the Perl script comes into play) and then those markdown files are generated by jekyll and posted to github. With a bit more scripting, I can smooth out the wrinkles and automate this.

Looks promising.

**Comment by nikitavoloboev** [comment]
Your wiki looks great, can't wait to see it grow 🌱

**Comment by sdondley** [comment]
Thanks. And thanks for re-igniting my interest in this kind of knowledge sharing. When I bumped into your website a couple of weeks back, I was excited to see someone using the web the way it was originally envisioned. I believe you are doing pioneering work.
