### ISSUE TITLE
Why are you following 6.5k people on github?

### ISSUE THREAD

**Issue by strdr4605** [nikitavoloboev/ama#55]
Every time I open the home page of GitHub I see only notifications from you 
__nikitavoloboev started following jaysonsantos and 21 other users__
__nikitavoloboev starred 63 repositories__
__nikitavoloboev started following olivierbrcknr and 35 other users__

Do you have a bot that does it all for you?
I see this as a good way to promote others, how does it benefit you?
Isn't your GitHub feed meaningless as too much info?

**Comment by nikitavoloboev** [comment]
I try to expose myself to many different ideas & tools so those 6.5k people made or did something I found of interest.

It is hard to manage. There is no bot and I archive feeds when I don't have time to view them. 

https://twitter.com/nikitavoloboev/status/1317435288889810944

**Comment by nikitavoloboev** [comment]
Also most of the things I do find interesting, I add to my wiki. Like in [this commit](https://github.com/nikitavoloboev/knowledge/commit/311453b658c22186274da94e82bd5e927a94748f).

**Comment by strdr4605** [comment]
Got it. I also know a guy that has a repo like yours. Will think about doing it myself. 

P.S. If you have long READMEs you can try [jump2header](https://github.com/strdr4605/jump2header).
