### ISSUE TITLE
What steps do your alfred workflow follows? (I don't have a mac nor a viewer and want to do something like it for Win)

### ISSUE THREAD

**Issue by jclozanoc** [nikitavoloboev/ama#56]
Hi, 

I saw the alfred workflow you have for accessing your personal wiki and think its awesome, unfortunately i don't have constant access to a mac to open the workflow and figure out how to do something similar on Windows, could you share the high level steps it follows or a link to a viewer?

**Comment by nikitavoloboev** [comment]
Not sure what you mean. What do you want to achieve?

**Comment by jclozanoc** [comment]
I want to have a workflow like yours on windows, for that i am not sure what to do so i think i can figure it out if i knew what steps follows your workflow

**Comment by nikitavoloboev** [comment]
Which workflow? Best to get a mac and try it yourself at some point, it's hard to explain what workflows do without getting a feel for them yourself.
