### ISSUE TITLE
Why do you use both Arq and Backblaze?

### ISSUE THREAD

**Issue by babramczyk** [nikitavoloboev/ama#58]
What's the use case there, vs. just using Backblaze?

https://wiki.nikitavoloboev.xyz/backups

**Comment by nikitavoloboev** [comment]
Backblaze is cheap storage. Arq is a nice client to do backups to some cloud storage service.

**Comment by babramczyk** [comment]
But what is Arq giving you that Backblaze's scheduled backups don't?

**Comment by nikitavoloboev** [comment]
I didn't try Backblaze scheduled backups, it might be good too :)

**Comment by babramczyk** [comment]
Got it.

Obviously not criticizing or anything, but just trying to understand if I was missing something, as I start to do backups myself. Especially since both Arq and Backblaze are paid services, and didn't want to pay for two if I didn't have to.

**Comment by nikitavoloboev** [comment]
Yeah, backblaze is cheapest option I think. I chose Arq as I read good reviews on its client and it's done quite well and not a subscription which is nice. 😄

**Comment by devnoname120** [comment]
@nikitavoloboev Arq 7 + cheap storage such as [Hetzner's storage](https://www.hetzner.com/storage/storage-box) becomes quickly cheaper than the subscription. Can even buy two storage boxes (one in Germany, one in Finland) for an affordable cross-geo replication. rsync.net's [special secret pricing](https://www.rsync.net/products/rclone.html) is even cheaper if you need less than 200 GB of storage.
