### ISSUE TITLE
What pdf viewer do you use?

### ISSUE THREAD

**Issue by pablojimeno** [nikitavoloboev/ama#59]
I saw you are selling a pdf version of your wiki in gumroad. What pdf viewer is the one in the picture?

![Everything I know Wiki as PDF](https://static-2.gumroad.com/res/gumroad-public-storage/variants/xr7i3usjhw9kwebn1xusogazzpxe/3298c3eb001bbed90f1d616da66708480096a0a1b6e81bd4f8a2d6e9b831d301)

**Comment by nikitavoloboev** [comment]
It's Apple Preview app.

**Comment by pablojimeno** [comment]
Ok I'm stuck with Catalina. Sorry.

**Comment by nikitavoloboev** [comment]
It's on Catalina too.
