### ISSUE TITLE
Would you say that the time and effort you spent to create and maintain your Zettelkasten(personal Wiki) was worth the effort?

### ISSUE THREAD

**Issue by cadleta** [nikitavoloboev/ama#60]
Let me start by saying that I am really impressed with all that you have accomplished and included in your personal wiki, as well as your projects. I have gone through a few different versions of my own personal wiki. I started with a folder of a few hundred [markdown docs with links in VS Code](https://youtu.be/vPjTyn0j1OY) and then moved over to RoamResearch. I have been finding that the time and effort to maintain and update the personal wiki is becoming a lot of work when starting out with the first few hundred notes. 

What I really want to know is do you get enough value out of your personal wiki to make the time and effort maintaining it worth the personal cost?

**Comment by nikitavoloboev** [comment]
I try to write tools to help adding stuff into wiki easily. Right now those are Alfred workflows I built. Mention them [here](https://wiki.nikiv.dev/other/wiki-workflow).

Recently moved to Obsidian for writing new notes. I think the effort is certainly worth it. Your system of notes will evolve with you if the system is fluid enough. Markdown files with some editor like Sublime Text or Obsidian is very fluid so can build many things on top of it.
