### ISSUE TITLE
What do you think of Eindhoven?

### ISSUE THREAD

**Issue by everythingness** [nikitavoloboev/ama#62]
Do you like living there? What are some of your favourite places? Do you buy your bread from Broodt — and if not why not? Maybe you know a better bakery?!

**Comment by nikitavoloboev** [comment]
It's not too bad. There's a [coffee place near train station](https://g.page/LUCIFER-BAR-KENNEDYPLEIN?share) I recently found that I love working from. Their iced coffee and cheese cake are great.

The city itself doesn't have that many things to see, can see it all in one day unlike Amsterdam but it has its charms mainly with nature and nice parks I think. 

I keep a list of my favorite places [here](https://goo.gl/maps/FezWmuT1ad7mkTLK9). Will try add more places there as I sometimes forget.

For bread, I don't go to any specific bakery, just get it from AH/Lidl/Jumbo. But maybe I should now that you mention it. 🤔

**Comment by everythingness** [comment]
maybe you like dumplings? do you know mantu? it’s an afghan dumpling and flavour and spice (bleekstraat 23) do a bloody good one, a little bit spicy but not nasty spicy, you know? it comes with a nice yoghurt sauce. but oh la la, the price! €7 for 3, but if you give them another €3 they’ll give you 6...

**Comment by nikitavoloboev** [comment]
Love dumplings and mantu. Will check out that bleekstraat 23 place. Thank you. ♥️
