### ISSUE TITLE
Spacebar mapping for palettes?

### ISSUE THREAD

**Issue by sublime392** [nikitavoloboev/ama#64]
I am just starting to look into using KM palettes. On https://wiki.nikiv.dev/macOS/apps/keyboard-maestro/km-macros you mention that you binded your Space key to be ⇧ + ⌃ + ⌥ modifier for ease of palette opening. I am missing where this part should be done. I don't see it in you Karabiner config. How is this binding done, or have things changed?

**Comment by nikitavoloboev** [comment]
I don't use it any more. The way it worked is that KM palette open was bound to a hotkey. Then I map with Karabiner spacebar + <key> to call that hotkey.
