### ISSUE TITLE
Thank you for the love for Graphic Walker

### ISSUE THREAD

**Issue by p1ng-request** [nikitavoloboev/ama#65]
Hey Nikita, thx for your interest in Graphic Walker!

I'm one of the contributors to Graphic Walker, a lightweight embeddable open-source alternative for legacy tools such as Tableau. We are also working on a project named RATH, which has automated the data analysis workflow with other cool features such as causal analysis. If you like Graphic Walker, definitely try RATH out!

RATH GitHub: https://github.com/Kanaries/Rath
RATH in browser: https://rath.kanaries.net

If you like RATH, could you update your learning wiki and link to our website? Our website link is https://kanaries.net

Thank you for the love :) we love data science as well, if you get any suggestions or feature requests, you can submit them anytime. Cheers!

**Comment by nikitavoloboev** [comment]
Looks nice. Will check it out.
