### ISSUE TITLE
Great site

### ISSUE THREAD

**Issue by hmorandell** [nikitavoloboev/ama#66]
Hi Nikita

I have browsed through your web site and your wiki and I'm impressed of all the knowledge you share! Big respect for that, you gave me so many ideas!
I was just wondering what tool your website is running and how you "build" your wiki? can you share me some infos on how to get started maybe doing a wiki like yours, like writing all down what I learn and what I know :-)?

thanks a lot
Hans

**Comment by nikitavoloboev** [comment]
Hey thanks for kind words.

Check [this page](https://wiki.nikiv.dev/other/wiki-workflow)
