### ISSUE TITLE
Recommended macOS clipboard app

### ISSUE THREAD

**Issue by Aqzhyi** [nikitavoloboev/ama#68]
Hello, currently I am using alfred.app and raycast.app,

but I would like to have a better way to manage and browse my clipboard.

My usage scenario is on macOS, I may need it for searching text, taking screenshots, or a certain piece of code.

Paid or free, both are acceptable.

Do you have any recommendations?

**Comment by nikitavoloboev** [comment]
I love and use [Alfred clipboard search](https://www.alfredapp.com/help/features/clipboard/).
