### ISSUE TITLE
re: question about https://macos.nikiv.dev/

### ISSUE THREAD

**Issue by dotmcdh** [nikitavoloboev/ama#69]
Hello Nikita!

I have five questions:
-  Are you sending the invoice after purchase? And is the price of $60 inclusive or exclusive of VAT?
-  Do you offer any discounts for Eastern European countries like EpicReact, etc.? (https://share.cleanshot.com/cnH5D14h)
-  I noticed that there are currently 3 chapters available out of 11. When do you plan to release all the chapters? Is it within this year or the next year?
- You can share sample lesson?
- Do you offer refund option like `I’ll refund your purchase within 30 days, no questions asked! etc? `

**Comment by dotmcdh** [comment]
@nikitavoloboev, can you respond to me? I'm interested in your course.

**Comment by nikitavoloboev** [comment]
> Are you sending the invoice after purchase? And is the price of $60 inclusive or exclusive of VAT?

I think Stripe should do this as payment goes through Stripe. I have not verified this though. If you do buy and get invoice, please respond so I will know. ♥️

> Do you offer any discounts for Eastern European countries like EpicReact, etc.?

Not currently but I can do one for you. In fact you can just name a price you think is fair and send it to [my PayPal](https://www.paypal.com/paypalme/nikivo). I will then unlock the course for you.

> I noticed that there are currently 3 chapters available out of 11. When do you plan to release all the chapters? Is it within this year or the next year?


By end of year, all chapters will be fully filled and done in quality.

> Do you offer refund option like I’ll refund your purchase within 30 days, no questions asked! etc?

Yes.

**Comment by dotmcdh** [comment]
@nikitavoloboev thank you for response.
`Not currently, but I can create one for you. In fact, you can simply name a price you think is fair and send it to [my PayPal](https://www.paypal.com/paypalme/nikivo). I will then unlock the course for you.`

When I send the username, is it the same as my GitHub account name? You can provide it there, via email, or maybe mention it in the payment title.

**Comment by nikitavoloboev** [comment]
> When I send the username, is it the same as my GitHub account name?

Yes. Can just provide it as message with paypal or something.

**Comment by dotmcdh** [comment]
@nikitavoloboev  ok I sent.

**Comment by nikitavoloboev** [comment]
Share your email, will enable course for you.

**Comment by nikitavoloboev** [comment]
Sent you access to your email. Thanks for buying it. ♥️
