### ISSUE TITLE
Programmatic access to a MindNode map, how?

### ISSUE THREAD

**Issue by gordonIanJ** [nikitavoloboev/ama#7]
How could I access a MindNode map programmatically? 

If a map is available as JSON, how could I find the URL?

**Comment by nikitavoloboev** [comment]
You can access the JSON structure of all MindNode maps by adding `.json` in the end of the URL.

For example [here](https://my.mindnode.com/ZKGETDkUaQUsL3q8q9z788CxG84oEHgDiT79GuzX.json) is JSON of [this map](https://my.mindnode.com/ZKGETDkUaQUsL3q8q9z788CxG84oEHgDiT79GuzX).
