### ISSUE TITLE
You okay?

### ISSUE THREAD

**Issue by Classic-Jack** [nikitavoloboev/ama#70]
Hey there, found your wiki on GitHub and read through your first diary entry from 2018, must have been really hard for you going through as much as you were.
I haven't read more yet but noticed that the looking back section hasn't had anything added since may  this year when your dog had to go to the vet, I'm out of nowhere just wondering if you're okay? I finished uni back in 2015 and became heavily depressed at the time and know how God damn difficult it is to get through exams regarding software development. You've done a far site more than me personal development wise and I applaud how much you've done, all I have is a Linux server I'm paying monthly for to do some personal side projects and all I've really done is host game servers for me and my friends like Minecraft and 7 days to die. Yeah you're awesome, keep doing what you're doing and I hope you're doing well.
Happy for you to delete this if you want to I'm unable to message on twitter

**Comment by nikitavoloboev** [comment]
Thank you for the message.

Yeah I am doing better. My earlier entries were bit down as I was indeed going through some financial and other troubles but it's bit better now.

Working on [new version of LA](https://github.com/learn-anything/learn-anything.xyz) and trying to get my health and other things up to speed too.

Minecraft and 7 days to die servers sound super fun. Would love to play those games at some point. Maybe after I release LA. 😺
