### ISSUE TITLE
What is your favorite method of learning Go?

### ISSUE THREAD

**Issue by HenkeDaniil** [nikitavoloboev/ama#8]

**Comment by nikitavoloboev** [comment]
Hey @HenkeDaniil 🙂 

My favourite method with learning anything is trying it out in practice and making or solving something. For Go, I just completed the [Go Tour](https://tour.golang.org/welcome/1) and then tried to use the language to solve some problems on Leetcode and making some command line tools and alfred workflows.

**Comment by HenkeDaniil** [comment]
Thank you for responding
